### ISSUE TITLE
Sometimes java.lang.IllegalStateException: attempt to re-open an already-closed object

### ISSUE THREAD

**Issue by xcesco** [xcesco/kripton#14]
Improve open in-write-mode check.

java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase:  xxxx
        at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
        at android.database.sqlite.SQLiteDatabase.isDbLockedByCurrentThread(SQLiteDatabase.java:602)
        at com.abubusoft.kripton.android.sqlite.AbstractDataSource.isOpenInWriteMode(AbstractDataSource.java:499)

**Comment by xcesco** [comment]
Resolved. Just improved isOpenInWriteMode in AbstractDataSource
